---
title: "Prototype"
author: "joahn-lab"
date: '2020-6-17'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

mylocation = "C:/Users/Byeongjun Cho/Documents/blog/blog/content/posts"
setwd(mylocation)

library(tidyverse)
library(httr)
library(XML)
library(xml2)
library(writexl)
library(tictoc)
library(sp)
library(rgdal)
library(geosphere)
library(shiny)
library(shinydashboard)
library(leaflet)
```

```{r, eval=FALSE, echo=FALSE}
url = "http://openapi2.e-gen.or.kr/openapi/service/rest/ErmctInfoInqireService/"

## 응급실 실시간 가용병상정보 조회 1번 오퍼레이터

operator = "getEmrrmRltmUsefulSckbdInfoInqire"
Servicekey = ""
pageNo = "1"
numOfRows = "99"

result_table_1 = tibble()
for (i in 1:10){
    queryParams = str_c("?serviceKey=", Servicekey, "&pageNo=", as.character(i), "&numOfRows=", "50")
    doc = xmlInternalTreeParse(str_c(url, operator, queryParams))
    rootNode = xmlRoot(doc)
    names = rootNode[[2]][['items']][['item']] %>%
        names()
    tmp_tbl = xmlToDataFrame(nodes = getNodeSet(rootNode, '//item')) %>%
        set_names(iconv(names, "UTF-8", "CP949") %>% unname()) %>%
        as_tibble()
    result_table_1 = result_table_1 %>% bind_rows(.,tmp_tbl)}

pageNo = "1"
numOfRows = "99" # "&pageNo=", pageNo, "&numOfRows=", numOfRows
operator = "getEgytListInfoInqire"

result_table_3 = tibble()
for (i in 1:402){
    QN = result_table_1[i,1]
    queryParams = str_c("?serviceKey=", Servicekey, "&QN=", QN)
    doc = xmlInternalTreeParse(str_c(url, operator, queryParams))
    rootNode = xmlRoot(doc)
    tmp_tbl_2 = xmlToDataFrame(nodes = getNodeSet(rootNode, '//items//hpid')) %>% as_tibble(.name_repair = "unique")
    tmp_tbl_3 = xmlToDataFrame(nodes = getNodeSet(rootNode, '//items//dutyName')) %>% as_tibble(.name_repair = "unique")
    tmp_tbl_4 = xmlToDataFrame(nodes = getNodeSet(rootNode, '//items//wgs84Lon')) %>% as_tibble(.name_repair = "unique")
    tmp_tbl_5 = xmlToDataFrame(nodes = getNodeSet(rootNode, '//items//wgs84Lat')) %>% as_tibble(.name_repair = "unique")
    tmp_tbl_2 = tmp_tbl_2 %>% bind_cols(.,tmp_tbl_3) %>% bind_cols(.,tmp_tbl_4) %>% bind_cols(.,tmp_tbl_5)
    result_table_3 = result_table_3 %>% bind_rows(.,tmp_tbl_2)}

hospital_score = read.csv("hospital_score_2.csv") %>% as_tibble()
hospital_score = hospital_score %>% 
    select(hpid, score) %>%
    mutate(score = score/100)
result_table_3 = result_table_3 %>% 
    rename(hpid = "text") %>%
    full_join(hospital_score, by = "hpid")
result_table_3 = result_table_3 %>% mutate(score = replace_na(score, 1))
result_table_3 = result_table_3 %>% drop_na() # 26군데 hospital_score 파일에서 갑툭튀
```
```{r, eval=FALSE, echo=FALSE}
EMD = readOGR(mylocation, "EMD")
to_crs = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
EMD_1 = spTransform(EMD, to_crs)
dong = EMD_1@data

for (i in 1:nrow(dong)){
    dong$x_coord[i] = parse_number(as.character(EMD_1@polygons[[i]]@labpt)[1])
    dong$y_coord[i] = parse_number(as.character(EMD_1@polygons[[i]]@labpt)[2])
}

dist_1 = list()
for (i in 1:nrow(dong)){
    dist_1[[i]] = c(dong$x_coord[i], dong$y_coord[i])
}

medi_1 = list()
for (i in 1:nrow(result_table_3)){
    medi_1[[i]] = c(parse_number(result_table_3$text2[i]), parse_number(result_table_3$text3[i]))
}


dong$score_num = 0
for (i in 1:length(dist_1)){
    for (j in 1:length(medi_1)){
        ifelse(distHaversine(dist_1[[i]], medi_1[[j]])<30000, 
               dong$score_num[i] <- dong$score_num[i]+result_table_3$score[j], 
               next)
    }
}
EMD_1 = sp::merge(EMD_1, dong)

SIG_1 = readOGR(mylocation, "SIG_1")

mainPanel(leafletOutput(outputId = "mymap", height = "900px", width = "125%"))

bins = c(0, 4.476, 13.739, 32.531, 40.033, 84, Inf)
pal = colorBin("YlGnBu", domain = SIG_1@data$score_num, bins = bins)

renderLeaflet({
    leaflet(SIG_1_simple) %>%
        setView(lng=127.7669,lat=35.90776, zoom=7.5) %>%
        addProviderTiles('CartoDB.Positron') %>%
        addPolygons(color='#444444', 
                    weight=2, opacity = 1.0, fillOpacity = 0.5, 
                    fillColor=~pal(score_num)) %>%
        addLegend(pal = pal, values = ~score_num, opacity = 0.7, title = NULL,
                  position = "bottomright")})
```

```{r eruptions, echo=FALSE}
CTPRVN_1 = readOGR(mylocation, "CTPRVN_1")

mainPanel(leafletOutput(outputId = "mymap", height = "900px", width = "125%"))

bins = c(0, 4.476, 13.739, 32.531, 40.033, 84, Inf)
pal = colorBin("YlGnBu", domain = CTPRVN_1@data$score_num, bins = bins)

renderLeaflet({
    leaflet(CTPRVN_1) %>%
        setView(lng=127.7669,lat=35.90776, zoom=7.5) %>%
        addProviderTiles('CartoDB.Positron') %>%
        addPolygons(color='#444444', 
                    weight=2, opacity = 1.0, fillOpacity = 0.5, 
                    fillColor=~pal(score_num)) %>%
        addLegend(pal = pal, values = ~score_num, opacity = 0.7, title = NULL,
                  position = "bottomright")})
```

```{r eruptions-1, eval=FALSE, echo=FALSE}
EMD_1 = readOGR(mylocation, "EMD_1")

mainPanel(leafletOutput(outputId = "mymap", height = 900, width = 600))

bins = c(0, 4.917, 14.413, 30.008, 34.322, 80.4, Inf)
pal = colorBin("YlGnBu", domain = EMD_1@data$score_num, bins = bins)

renderLeaflet({
    leaflet(EMD_1) %>%
        setView(lng=127.7669,lat=35.90776, zoom=7.5) %>%
        addProviderTiles('CartoDB.Positron') %>%
        addPolygons(color='#444444', 
                    weight=2, opacity = 1.0, fillOpacity = 0.5, 
                    fillColor=~pal(score_num)) %>%
        addLegend(pal = pal, values = ~score_num, opacity = 0.7, title = NULL,
                  position = "bottomright")})
```


```{r tabsets, eval=FALSE, echo=FALSE}
shinyAppDir(
  system.file("examples/06_tabsets", package = "shiny"),
  options = list(
    width = "100%", height = 550
  )
)
```
