---
title: Golden Time Project 회의록
author: ''
date: '2020-06-19'
slug: project-time-line
categories: []
tags: []
language: en
---

## 03.30자 회의
#### 프로젝트 후보 선정
후보
1. 기상변수를 고려한 농산물 가격 예측 모델

## 04.10자 회의
#### 프로젝트 후보 선정, 투표 진행
후보
1. 기상변수를 고려한 농산물 가격 예측 모델
2. 유기동물 찾기 서비스
3. 응급실 안내 서비스
  
투표를 통해 응급실 안내 서비스로 결정.

- 다음 주 회의 준비 사항
- 조병준: 아이디어 구체화

- 박경재, 정윤호: 해당 프로젝트의 기술적인 부분, 데이터 분석 활용 방법 고민 + 조병준님 기술적 질문 확인

- 이시우, 손지현, 서아론: 사업화 기획 방법 고민 및 기존 제품과의 차별성 두기, 벤츠마킹할만한 제품 있는지 찾아보기

## 04.13자 회의
#### 프로젝트 방향성 확정
- 제안된 서비스
  1. 응급의료기관, 구급차, AED(자동심장충격기), 일반 병·의원 진료시설 등 응급상황 대처시 필요한 정보를 안내, 추천 및 필터링하는 서비스
    - **한계점 : 응급상황 시 어플보다 119 서비스를 사용.**
      - 같은 기능을 하는 [의료원 어플리케이션](https://play.google.com/store/apps/details?id=kr.go.mw)
  2. **(확정)응급 의료 취약지 선정하는 데이터 분석 프로젝트**
    - 도시계획 관련 정책적 제언.
    - 현재 위치를 기반으로 응급의료 안전성을 검토해주는 서비스.
    - 해결할 일
      1. 사용할 수 있는 데이터 소스 찾기.
      2. 해당 응급 의료 취약지 분석 방안
  3. 응급 의료 상황 발생을 분석하는 서비스.
    - 백그라운드에서 정보 수집.
    - **한계점**
      1. **추가 장비의 필요성** : 생체 데이터가 필요하기 때문에, 추가 장비 구입해야할 가능성.
      2. **훈련 데이터셋의 부재 ** : 응급 상황에 대한 기존 데이터 부재. 예측 모델링 과정이 어려울 것.
      3. **실제 예측 정확도 측정** : 실제로 사고가 발생해야 정확도를 측정할 수 있다는 점에서 한계.
  4. 급여/비급여 항목에 대한 의료보험 개인화 서비스.

- 서비스 선정 기준
  - 사회적 가치 vs 수익성
    - 수익성을 논하기보단, **완성도** 있고 **사회적 가치를 제공**할 수 있는 서비스 기획에 목적.


- 다음 주 회의
  1. 응급 의료 취약지 선정 프로젝트로 선정.
      1. 응급 시설이 부족한 지역 시각화
      1. 의료 사각지대 기준 설정
      1. 알고리즘, 데이터 기반 현재 위치의 안정성을 real-time으로 제공.
  1. **해야할 일**
      1. **분석에 활용 가능한 데이터**
      1. **참고할 논문 및 자료**
      1. (추가 논의) 알고리즘, 분석 기준
  

## 04-20 회의
#### 응급 의료 취약지 분석 방안 논의
#### 박경재님) 데이터 처리 pipeline 코드 작성.
1. **분석 방법** : 이송차량 분석, 이에 따라 해당 위치에서 인근 응급 시설까지 접근성 측정.
2. 완료
  - 데이터 수집, 인코딩, 모델링까지 이어지는 pipeline 제작.
  
  
## 04-26 회의
#### 유사한 분석 사례, 참조 자료 조사 및 발표
#### 분석에 사용할 3가지 Factor 선정.
1. 응급 시설의 수로 응급 취약지 선정의 한계.
2. 유사 분석 사례
  1. [“응급실과 119 안전센터의 접근성을 고려한 응급의료 취약지 분석”]("https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002409209")
    - 상세하지 않고, 농촌 위주의 분석
    - 병상 수와 입원실 수에 대한 추가 분석이 필요할 것 같다.
  2. 2017/2018 의료취약지 모니터링 연구
  (보건복지부 국립중앙의료원)
  3. NEDIS(국가응급진료정보망) 2017-2018 통계연보 
3. 분석 과정, 결과 논의
  - 코로나와 관련해 비 의료 시설이 의료 시설로 전환하는 사례가 발생하는데, 이에 따른 대체 응급 의료 시설의 공급 가능성 분석
  - 접근성 분석
    1. 어떤 변수들을 고려?
    2. 2차원 좌표를 기준으로 원 범위 내의 응급 의료 시설 계산.
  - 회귀 모델을 사용, 미래의 응급 의료 취약지 예측.
3. **고려할 변수**
    1. 접근성
      - 30분 거리 이내의 응급 시설 수.
    2. 응급 의료 인프라
      - 병상 수 / 의료진 수
      - “심뇌혈관질환이나 증증외상질환에 대한 처치가 어려운 취약한 의료시설”, 각 응급시설마다 처리할 수 없는 응급 질환들이 있고, 이런 질환들에 대한 가중치를 부여, 응급 의료 인프라 점수를 계산.
    3. 취약 인구 비율
      - 응급 의료는 특히 영유아, 고령인구층에 필요한 서비스. 해당 취약 인구 비율을 반영한다면 더 나은 응급 의료 취약지 선정이 될 것.


## 05-03 회의
#### 이시우님) 활용 가능한 통계 모델 조사
#### 타임라인 설정
1. 확정 변수
    1. 접근성
    2. 의료 시설 인프라
    3. 인구
2. 사용할 수 있는 통계 모델 조사
  - 이시우님
    - 시계열 분석, 회귀 분석에 따라 미래 의료 취약지역 예측 모델.
3. 타임라인 설정
    1. ~05.15 : 데이터 분석에 다룰 모형, 데이터 확정
    2. ~05.30 : 데이터 분석 코드 작성 + 추가 분석 사항
    3. ~06.07 : 데이터 분석 시각화
    4. ~06.22 : 발표자료 및 블로그 퍼블리싱.

## 05-12
#### 이시우님 주도) 활용 가능한 통계 모델 스터디
1. Predictive Analysis
2. Prescriptive Analysis
3. Causal Analysis

- 예측 모델을 통해 인구수의 변화에 따라 미래 응급 의료 취약지를 예측할 수 있을 것 같다.
- prescriptive Analysis를 통해 응급 시설 점수를 측정하는 방법 고려해보면 좋을 것 같다.

- 활용 가능한 데이터셋
    1. 응급의료정보조회서비스(국립중앙의료원) - 공공데이터포털에 있음(2020 ver)
    2. 119 안전센터 GIS 파일데이터(소방청) - 공공데이터포털에 있음(2018 ver)
    3. 읍면동 단위 주민등록인구 (행정안전부) + XsDB(유료)


## 05-18 회의
#### 병원 등급 / 인구 밀도 / 위치 데이터 / 시각화 방안
#### 활용 가능한 자료 조사 및 공유
- 논의 사항  
  1. 기존 병원 등급 자료 확인 필요.
      - [공공보건의료지원센터](http://www.healthmap.or.kr/)
      - [중앙응급의료센터](https://www.e-gen.or.kr/nemc/business_medical_institution_evaluation.do?tabId=3)
  2. 인구 밀도활용 방안
    - [인구 밀도 자료](https://www.notion.so/1dc44f8501af4720a2a8bedf13f94077)
  3. 위치 데이터
    - 국도 격자 100m간격 라벨링
    - 행정 구역 읍, 면, 동, 리 기준 라벨링
  4. 교차 검증
    응급 의료 인프라 점수의 신뢰성에 대한 논의.
    - 나라에서 지정한 응급의료 취약지와 비교?
      → 추가적으로 변수를 입력하는 상황에서, 나라에서 지정한 응급의료 취약지와 비교하는 것보다 추가 분석을 통해 의미를 부여하는 방식. 
  5. 시각화 방안
    - python 혹은 R을 통해 진행.
  6. R markdown을 통해 페이지 작성.
  7. (박경재님)전체 프로젝트 flowchart 작성

- 추가 논의할 점)
    1. 응급 상황 종류 - 골든타임에 따른 scoring 여부.
    2. 현재 open api 요청해서 xml parsing 하는과정은 완료하였는데, 다른 형태(json 등)에 대한 크롤링 코드작성중
    3. 추후 머신러닝을 위한 Feature extraction(특징추출 -> 인코딩) 예정



## 05-21 회의
#### 응급 의료 인프라, 인구 밀도 -  점수화 / 반영 방법
1. 응급 의료 시설 인프라
    1. 점수화 : **PCA**.각 의료 시설마다 attributes를 갖고 있고 우리가 이를 추출해서, 각 응급 시설별로 가중치 부여.
    2. 반영 방법
      - 특정 위치에서 30분내로 도달할 수 있는 응급의료 시설이 없다면 1차적으로 의료취약지역.
2. 추가 논의 사항
    1. 인구 데이터 활용 방안
    2. 최소 비용 최대 효율 병원 입지 선정
    3. 특정 지역을 세분화 기준
  

## 05-22
#### 박경재님) 접근성 분석 코드 작성 / 시각화 - python
1. API 요청, 402개의 병원 위도, 경도 좌표
2. 행정 구역의 읍면리 중 '리' 단위로 나눠 폴리곤 좌표 해석 코드 작성
3. 해당 행정 구역에서 특정 거리 이내의 응급 의료 시설 분석하는 코드 작성.
4. 해당 코드 시각화.

## 05-24 오프라인 회의
#### 중간 발표 자료 관련 회의
- [중간 발표 자료](https://www.notion.so/Emergency_Analysis-087b8f606ecd48cc9c7ddf2e3e0a4494) 작성

## 05-26 
#### 조병준님) API 데이터 추출 - Python → R 치환
- 전국응급의료기관 API에서 필요 변수들 추출, 엑셀 파일로 저장.(PCA 분석에 사용할 예정)
  1. 기본 정보 조회
  2. 중증 질환자 수용 가능 여부
  3. 의료 시설 위치
  4. 외상센터 기본정보 조회

## 05-31
#### 이시우님) PCA 분석 중간 현황
- 분석 결과
  - 약 30개의 변수를 응급 의료 인프라 지수에 반영.
  - 병원 점수라 볼 수 있는 축 확인.
  - 이후 몇 개의 변수를 제거할 예정.

- 추후 해야할 일
  1. EDA, 공선성, 특이값에 대한 논의.
  2. 2개의 파일을 합치면서 탈락된 100여개의 병원.
  3. 병원점수를 구성하는 축에 대한 분석.

## 06-07
#### 조병준님) python code → R code 시각화 진행
#### 이시우님) 응급 의료 인프라 점수 추가
#### 박경재님) DB migraion 추가
1. Python → R 치환 작업
  기존에 작성했던 접근성에 대한 시각화(박경재님)는 파이썬 코드로 작성되었기 때문에, 이를 Rmd 파일로 통합하기 위하여 R 코드로 치환하는 과정을 진행.
  - 기존 접근성에 대한 python 코드를 리플렛 패키지를 통한 시각화 사전 작업 완료.

2. 응급 의료 인프라 점수 분석
    1. 공선성 진단 추가
    2. 결측값, 탈락된 병원에 대한 평균 점수로 imputation
  
3. JPA + Springboot 이용 DB migration (H2에 테스트완료) → AWS S3 환경설정후 Docker 컨테이너에 적용, 배포 자동화 (AWS Fargate)

## 06-08 회의
#### 응급 의료 인프라 점수 논의
#### 일반 병원 포함 여부 논의
1. 응급 의료 인프라 점수에 대한 논의
  - 사용 가능한 응급실 수에 초점을 맞출 경우, 국가에서 지정한 응급의료 시설 평가와 상관계수가 가장 높았음.
  - 하지만, 다른 변수도 고려하는 것이 프로젝트의 목표이므로, 추가된 변수에 따라 바뀐 병원 점수 축에 대한 추가적 의미를 부여하는 것으로 합의.
2. API에 있는 일반 병원 포함 여부
  - 일반 병원을 모두 포함할 시 약 90,000개의 병원에 대한 처리 작업이 필요.
  - 행정구역 '리'단위로 처리할 경우, 너무 많은 리소스가 발생. 진행할 수 없다는 것에 동의.

## 06-16 회의
#### 시각화, 대시보드 진행상황 공유

## 06-17
#### 조병준님) [shiny를 통한 응급 의료 점수 시각화 완료](https://joahn-lab.shinyapps.io/shiny/)


## 06-18
#### 박경재님) 최소비용, 최대효율 코드 작성
#### 박경재님) 접근성 기준을 30km로 조정, 시각화

## 06-19
- 샤이니 시각화(대시보드) 완료.
  1. 병원명 + 점수 시각화
  2. 히스토그램
  3. csv파일 다운로드
